### ISSUE TITLE
Error: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mnarra-varmour** [terraform-docs/terraform-docs#630]
With output-values enabled the command throws panic: runtime error: invalid memory address or nil pointer dereference
Otherwise works well.

> terraform output -json > output_val.json
> terraform-docs markdown table --output-values --output-values-from output_val.json .

### OR
enable output-values in .terraform-docs.yaml
```
 output-values:
   enabled: true
   from: "output_val.json" 
```
and run 

> terraform-docs markdown table --output-mode inject . 

### Environment information
> terraform-docs version v0.16.0 darwin/amd64
> Terraform version v1.0.7
> Both on Mac and ubuntu

**Comment by mnarra-varmour** [comment]
### Full Error log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14d2cc1]

goroutine 1 [running]:
github.com/terraform-docs/terraform-docs/terraform.loadOutputs(0xc0000a6980, 0xc0000b2000)
	/private/tmp/terraform-docs-20211025-36170-qku1qy/terraform-docs-0.16.0/terraform/load.go:297 +0x2e1
github.com/terraform-docs/terraform-docs/terraform.loadModuleItems(0x7ff7bfeffb40, 0xc0000b2128)
	/private/tmp/terraform-docs-20211025-36170-qku1qy/terraform-docs-0.16.0/terraform/load.go:70 +0x111
github.com/terraform-docs/terraform-docs/terraform.LoadWithOptions(0xc0000b2000)
	/private/tmp/terraform-docs-20211025-36170-qku1qy/terraform-docs-0.16.0/terraform/load.go:41 +0x3e
github.com/terraform-docs/terraform-docs/internal/cli.generateContent(0xc0000b2000)
	/private/tmp/terraform-docs-20211025-36170-qku1qy/terraform-docs-0.16.0/internal/cli/run.go:326 +0x25
github.com/terraform-docs/terraform-docs/internal/cli.(*Runtime).RunEFunc(0xc0000a02c0, 0xc0001e7d60, {0xc0001e7d38, 0x0, 0x0})
	/private/tmp/terraform-docs-20211025-36170-qku1qy/terraform-docs-0.16.0/internal/cli/run.go:134 +0x1f8
github.com/spf13/cobra.(*Command).execute(0xc0000b7180, {0xc000096420, 0x6, 0x6})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000b6000)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/terraform-docs/terraform-docs/cmd.Execute()
	/private/tmp/terraform-docs-20211025-36170-qku1qy/terraform-docs-0.16.0/cmd/root.go:37 +0x25
main.main()
	/private/tmp/terraform-docs-20211025-36170-qku1qy/terraform-docs-0.16.0/main.go:20 +0x19```

**Comment by mnarra-varmour** [comment]
@gshel ++

**Comment by akorp** [comment]
I am getting same error when json file with terraform output values is empty (has empty block`{}`), which happens when terraform module does not has any output yet.

```
> cat terraform-docs.config
...
/
output-values:
  enabled: true
  from: "path-to/tfoutput.json"
...
```
```
> cat tfoutput.json
{}
```
```
> terraform-docs . --config terrafor-docs.config
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14d2cc1]

goroutine 1 [running]:
github.com/terraform-docs/terraform-docs/terraform.loadOutputs(0xc00013a700, 0xc000126000)
	/private/tmp/terraform-docs-20211025-36170-qku1qy/terraform-docs-0.16.0/terraform/load.go:297 +0x2e1
github.com/terraform-docs/terraform-docs/terraform.loadModuleItems(0x7ff7bfeff757, 0xc000126128)
	/private/tmp/terraform-docs-20211025-36170-qku1qy/terraform-docs-0.16.0/terraform/load.go:70 +0x111
github.com/terraform-docs/terraform-docs/terraform.LoadWithOptions(0xc000126000)
	/private/tmp/terraform-docs-20211025-36170-qku1qy/terraform-docs-0.16.0/terraform/load.go:41 +0x3e
github.com/terraform-docs/terraform-docs/internal/cli.generateContent(0xc000126000)
	/private/tmp/terraform-docs-20211025-36170-qku1qy/terraform-docs-0.16.0/internal/cli/run.go:326 +0x25
github.com/terraform-docs/terraform-docs/internal/cli.(*Runtime).RunEFunc(0xc00011e280, 0xc0001e5d60, {0xc0001e5d38, 0x0, 0x0})
	/private/tmp/terraform-docs-20211025-36170-qku1qy/terraform-docs-0.16.0/internal/cli/run.go:134 +0x1f8
github.com/spf13/cobra.(*Command).execute(0xc00012e000, {0xc00019c050, 0x3, 0x3})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00012e000)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/terraform-docs/terraform-docs/cmd.Execute()
	/private/tmp/terraform-docs-20211025-36170-qku1qy/terraform-docs-0.16.0/cmd/root.go:37 +0x25
main.main()
	/private/tmp/terraform-docs-20211025-36170-qku1qy/terraform-docs-0.16.0/main.go:20 +0x19
```

**Comment by gettek** [comment]
Issue persists in v0.19.0.
I don't see how this can be an issue with "unapplied" outputs as tfdocs is particularly useful when documenting Modules
