### ISSUE TITLE
Can't store Docker Output

### ISSUE THREAD

**Issue by ASHR4** [terraform-docs/terraform-docs#653]
### Describe the bug

Trying to store the output when running terraform-docs when using the docker image. 

I want to do this for error handling as there is no hard-fail option.

I suppose this can be split into a bug and feature request, either having the ability to store docker output instead of output directly into the terminal and/or having a --hard-fail option, if possible.

### How can we reproduce it?

Run Docker and try and store to a variable (I'm using PowerShell)

### Environment information

Terraform-Docs version v0.16.0
Ubuntu-Latest on Azure Devops Agent

**Comment by adminph-de** [comment]
I am facing the same issue in my DevOps Pipeline.

by executing:

```bash
TF_DOCS="/src"
TF_OUTPUT="/src/build/4456"
docker container run --rm \
--volume ${TF_DOCS}:/terraform-docs \
--volume ${TF_OUTPUT}:/terraform-output \
-u $(id -u) quay.io/terraform-docs/terraform-docs:latest \
  markdown /terraform-docs \
  --show inputs \
  --show outputs \
  --output-check \
  --output-file output.default.md \
  --output-mode inject \
  --output-values \
  --output-values-from /terraform-output/default.output.json
```

```log
able to find image 'quay.io/terraform-docs/terraform-docs:latest' locally
latest: Pulling from terraform-docs/terraform-docs
5843afab3874: Pulling fs layer
2d4a2b6c581c: Pulling fs layer
5843afab3874: Verifying Checksum
5843afab3874: Download complete
2d4a2b6c581c: Verifying Checksum
2d4a2b6c581c: Download complete
5843afab3874: Pull complete
2d4a2b6c581c: Pull complete
Digest: sha256:e24bf3fe70d15eeda95399f4fa5c70260cf4dfffbff4fb66931095d8d7ba9074
Status: Downloaded newer image for quay.io/terraform-docs/terraform-docs:latest
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x993c9b]

goroutine 1 [running]:
github.com/terraform-docs/terraform-docs/terraform.loadOutputs(0xc0000c9480, 0xc00009e900, 0xc000077700, 0x5, 0x8, 0xc00006b600, 0x3)
	/home/runner/work/terraform-docs/terraform-docs/terraform/load.go:297 +0x35b
github.com/terraform-docs/terraform-docs/terraform.loadModuleItems(0xc0000c9480, 0xc00009e900, 0xc0000c9480, 0x0, 0x0)
	/home/runner/work/terraform-docs/terraform-docs/terraform/load.go:70 +0x1ad
github.com/terraform-docs/terraform-docs/terraform.LoadWithOptions(0xc00009e900, 0x801ce0, 0xc00009e9b8, 0x801c60)
	/home/runner/work/terraform-docs/terraform-docs/terraform/load.go:41 +0x6f
github.com/terraform-docs/terraform-docs/internal/cli.generateContent(0xc00009e900, 0x0, 0x0)
	/home/runner/work/terraform-docs/terraform-docs/internal/cli/run.go:326 +0x2f
github.com/terraform-docs/terraform-docs/internal/cli.(*Runtime).RunEFunc(0xc0001cd1c0, 0xc0001ff680, 0xc0000f46c0, 0x1, 0xc, 0x0, 0x0)
	/home/runner/work/terraform-docs/terraform-docs/internal/cli/run.go:134 +0x145
github.com/spf13/cobra.(*Command).execute(0xc0001ff680, 0xc0000f4600, 0xc, 0xc, 0xc0001ff680, 0xc0000f4600)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001fea00, 0x0, 0x60, 0x7f09094b75b8)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/terraform-docs/terraform-docs/cmd.Execute(0xbfcca0, 0xc000082058)
	/home/runner/work/terraform-docs/terraform-docs/cmd/root.go:37 +0x2b
main.main()
	/home/runner/work/terraform-docs/terraform-docs/main.go:20 +0x25
```

DevOps Agent(s): ubuntu-18.04, ubuntu-20.04,  and ubuntu-22.04
